FROM dkarchmervue/python27-opencv

MAINTAINER Ivan Kuznetsov <ivan.kuznetsov1@gmail.com>

########################################
#
# Image based on dkarchmervue/python27-opencv
#
#   with Python 2.7
#   and OpenCV 3 
#   plus a bunch of build essentials
#######################################

RUN sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
RUN apt-get install -y -q python-pygame
RUN apt-get install -y -q python-matplotlib
